### ISSUE TITLE
Flash Loan - PancakeSwap V2 Triangular Arbitrage Issue

### ISSUE THREAD

**Issue by jnoweb** [CryptoWizardsNet/flash-loan-arbitrage-triangular#2]
Hi,

Working with `Flash Loan - PancakeSwap V2 Triangular Arbitrage`I get this error during chapter 83. Any ideas on how to resolve?

`npx hardhat test

  FlashLoan Contract
    1) "before each" hook for "general test"

  Token Contract
hello
    ✔ prints hello

  1 passing (3s)
  1 failing

  1) FlashLoan Contract
       "before each" hook for "general test":
     Error: The response reported error `-32000`: `missing trie node`. (optional data: None). Request: {"id":3,"jsonrpc":"2.0","method":"eth_getBalance","params":["0x3c44cdddb6a900fa2b585dd299e03d12fa4293bc","0x25fab28"]}
  

An unexpected error occurred:

[Error: The response reported error `-32000`: `missing trie node`. (optional data: None). Request: {"id":3,"jsonrpc":"2.0","method":"eth_getBalance","params":["0x3c44cdddb6a900fa2b585dd299e03d12fa4293bc","0x25fab28"]}] {
  code: 'GenericFailure'`

**Comment by janetdeerfield** [comment]
Here's one ChatGPT response:

The error message you're encountering (`missing trie node`) suggests there
is an issue with the state of the blockchain node you're interacting with.
This often happens when there is a corruption in the local blockchain data
or when the node is unable to retrieve the necessary state information.

Here are several steps you can take to troubleshoot and resolve this issue:

1. **Restart your local blockchain node**: If you're using a local Ethereum
node like Ganache or Hardhat Network, try restarting it to clear any
temporary issues or corrupted state.

2. **Reinitialize your local blockchain state**: Sometimes the blockchain
state may become corrupted. Resetting the state can help.
   - For Ganache, you can simply close and reopen it.
   - For Hardhat Network, you can delete the `cache` and `artifacts`
folders in your project directory, and then restart the network by running
`npx hardhat node` again.

3. **Check for conflicts in your setup**:
   - Ensure there are no conflicting versions of dependencies in your
project.
   - Verify that your Hardhat configuration is correctly set up, especially
if you have custom configurations for networks.

4. **Ensure your environment is up to date**:
   - Update your Node.js to the latest stable version.
   - Ensure Hardhat and all related dependencies are up to date. You can
update Hardhat and its dependencies by running:
     ```bash
     npm update --save-dev @nomiclabs/hardhat-ethers ethers
@nomiclabs/hardhat-waffle
     ```

5. **Debugging the test code**:
   - The issue might also be related to the way your test is set up.
Double-check the `beforeEach` hook in your test suite to ensure it's
correctly configuring the test environment.
   - Add logging to your `beforeEach` hook to pinpoint where the issue
occurs. This can help identify if a specific call is causing the issue.

6. **Inspect the failing `eth_getBalance` call**:
   - Ensure the address `0x3c44cdddb6a900fa2b585dd299e03d12fa4293bc` is
valid and the blockchain node is correctly handling it.
   - You might want to run this specific call in isolation to see if it
consistently fails or if it only fails within the test.

If these steps don't resolve the issue, consider the following:

- **Use a different blockchain node**: If you're using a local node, try
switching to another one or using an online service like Infura or Alchemy.
- **Reinstall dependencies**: Sometimes, a clean slate helps. Delete
`node_modules` and run `npm install` again.

If the problem persists, please provide more details about your setup, such
as the configuration files and the specific code in your `beforeEach` hook,
to enable a more thorough investigation.
